include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    # workaround for https://github.com/dart-lang/sdk/issues/42910
    - 'example/**'

# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    prefer_single_quotes: false